### ISSUE TITLE
Error "Package android.support.v4.content does not exist"

### ISSUE THREAD

**Issue by NeliHarbuzava** [react-native-community/react-native-geolocation#39] opened 2019-06-18 08:51 UTC
## Environment

```
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
      Memory: 1.05 GB / 7.86 GB
    Binaries:
      Node: 10.16.0 - D:\Programs\Node.js\node.EXE
      npm: 6.9.0 - D:\Programs\Node.js\npm.CMD
```

## Platforms
Android

## Versions
- Android 9
- react-native-geolocation: 1.4.2
- react-native: 0.59.8
- react: 16.8.6

## Description
When I run `react-native run-android` I got this error:

```
Task :@react-native-community_geolocation:compileDebugJavaWithJavac FAILED
D:\Projects\project\node_modules\@react-native-community\geolocation\android\src\main\java\com\reactnativecommunity\geolocation\GeolocationModule.java:21: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
D:\Projects\project\node_modules\@react-native-community\geolocation\android\src\main\java\com\reactnativecommunity\geolocation\GeolocationModule.java:274: error: cannot find symbol
    int finePermission = ContextCompat.checkSelfPermission(getReactApplicationContext(), android.Manifest.permission.ACCESS_FINE_LOCATION);
                         ^
  symbol:   variable ContextCompat
  location: class GeolocationModule
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@react-native-community_geolocation:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```

## Reproducible Demo
Content of android/app/build.gradle:

```
apply plugin: "com.android.application"
apply plugin: "kotlin-android"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
        entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"
apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion 28
    buildToolsVersion "29.0.0-rc3"

    signingConfigs {
        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
    }

    defaultConfig {
        applicationId "com.project"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 96
        versionName "1.51.15"
        ndk {
            abiFilters "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86_64"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a": 1, "x86": 2, "arm64-v8a":3, "x86_64":4]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation project(':@react-native-community_geolocation')
    implementation project(':@react-native-community_netinfo')
    compile project(':react-native-static-server')
    compile project(':react-native-keep-awake')
    compile project(':react-native-file-viewer')
    compile project(':react-native-webview')
    compile project(':react-native-zip-archive')
    compile project(':rn-fetch-blob')
    compile project(':react-native-fs')
    compile project(':react-native-spatial')
    compile project(':react-native-fs')
    compile project(':react-native-sqlite-2')
    compile 'com.google.android.gms:play-services-location:+'
    compile project(':react-native-sensitive-info')
    compile project(':react-native-sentry')
    compile project(':react-native-image-picker')
    compile project(':react-native-device-settings')
    compile project(':react-native-linear-gradient')
    compile project(':react-native-vector-icons')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile 'com.facebook.fresco:fresco:1.9.0'
    compile 'com.facebook.fresco:animated-gif:1.9.0'
// IN CASE YOU NEED WEBP SUPPORT / MAKE SURE TO CHANGE THIS TOO TO 1.9.0
    compile 'com.facebook.fresco:animated-webp:1.9.0'
    compile 'com.facebook.fresco:webpsupport:1.9.0'
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}

task copyFonts(type: Copy) {
    from '../../assets/fonts'
    into 'src/main/assets/fonts'
}

// Copy map.html and its files
task copyMapHTML(type: Copy) {
    from '../../src/components/presentational/OLMap/webview/map.html'
    into 'src/main/assets/OLMap'
}

task copyMapSRC(type: Copy) {
    from '../../assets/src/components/presentational/OLMap/webview'
    into 'src/main/assets/OLMap'
}

task copyLogo(type: Copy) {
    from '../../assets/images/login_logo.png'
    into 'src/main/assets'
}
// Note that you may need to add other build variants
gradle.projectsEvaluated {
    bundleDebugJsAndAssets.dependsOn([copyMapHTML, copyMapSRC, copyFonts, copyLogo])
    bundleReleaseJsAndAssets.dependsOn([copyMapHTML, copyMapSRC, copyFonts, copyLogo])
}

```

**Comment by NeliHarbuzava** [comment] 2019-06-18 09:49
I got this broken after upgrading to AndroidX. I was forced to update to AndroidX because of some errors I get few hours before. See this thread ([https://stackoverflow.com/questions/56642369/android-material-and-appcompat-manifest-merger-failed-in-react-native-or-expokit](https://stackoverflow.com/questions/56642369/android-material-and-appcompat-manifest-merger-failed-in-react-native-or-expokit)). And after upgrading some react-native-community packages, like geolocation(this) and netinfo are broken now.

**Comment by patrickmwatson** [comment] 2019-06-18 17:32
Same, not sure what to do

**Comment by matt-oakes** [comment] 2019-06-19 05:05
This is likely happening because one of your dependencies is now using AndroidX instead of the support library. This means all dependencies need to use it, but this one hasn't been upgraded yet.

There is a tool which can handle the conversion for you, but it's currently experimental. You you take a look at the instructions here and report back if it fixes you issue?

https://github.com/mikehardy/jetifier#usage-for-source-files

**Comment by NeliHarbuzava** [comment] 2019-06-19 07:20
@matt-oakes Nope, none of my dependencies is using AndroidX. I just had in my build.gradle Google Services with '+' version, which means the last one. 17 June Google announced new major release which broke my app. I tried upgrade to AndroidX, but some RN plugins and 'react-native-geolocation' too does not support AndroidX yet. So for now I just set Google Service version to 16.0.0. It is temp fix for broken RN plugins, because I heard that from version 0.60 React Native will use AndroidX by default.

**Comment by matt-oakes** [comment] 2019-06-19 14:51
This library actually doesn't directly use any support library or AndroidX dependencies, so your issue is likely with other libraries.

I would recommend taking a look at the link above, and maybe this discussion for some background on the problem and why that solution is a working one:

https://github.com/react-native-community/discussions-and-proposals/issues/129

I'm going to close this issue now, but feel free to post a comment on one of the other threads if the Jetifier solution does not work for you.

**Closed by matt-oakes** 2019-06-19 14:51 UTC
Labels: bug

**Comment by dancomanlive** [comment] 2019-07-04 06:12
@react-native-community/geolocation/android/src/main/java/com/reactnativecommunity/geolocation/GeolocationModule.java:21: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^

I had to replace accordingly: https://developer.android.com/s/results/?q=ContextCompat

**Comment by matt-oakes** [comment] 2019-07-04 17:46
@dancomanlive To do this automatically you should take a look at this project https://github.com/mikehardy/jetifier

**Comment by bockc** [comment] 2019-07-12 09:33
Now that RN 0.60 is out, will you update your dependencies to support AndroidX ?

**Comment by stigmat4j** [comment] 2019-07-15 06:35
Have news?

**Comment by Heru6664** [comment] 2019-07-17 15:51
does anyone solve it? i have same issue

**Comment by rewieer** [comment] 2019-07-19 15:31
Doesn't work when running with run-android but works fine when building directly from Android Studio.

**Comment by msqar** [comment] 2019-07-24 01:08
I get the same error but a different stacktrace:
```
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/marian-mac/Documents/dev/purrpies/node_modules/@react-native-community/geolocation/android/src/main/java/com/reactnativecommunity/geolocation/GeolocationModule.java:21: error: package android.support.v4.content does not exist
import android.support.v4.content.ContextCompat;
                                 ^
/Users/marian-mac/Documents/dev/purrpies/node_modules/@react-native-community/geolocation/android/src/main/java/com/reactnativecommunity/geolocation/GeolocationModule.java:274: error: cannot find symbol
    int finePermission = ContextCompat.checkSelfPermission(getReactApplicationContext(), android.Manifest.permission.ACCESS_FINE_LOCATION);
                         ^
  symbol:   variable ContextCompat
  location: class GeolocationModule
2 errors
```

**Comment by bockc** [comment] 2019-07-24 09:59
@msqar If I remember correctly you need to jetify your project to fully support AndroidX. Try `npm i -D jetifier ; npx jetify`. If you correctly configured your android project to use AndroidX, this should fix the last issues. Let me know if this worked.

**Comment by msqar** [comment] 2019-07-24 12:10
@bockc Tried, but whenever i run `npx react-native run-android` or `npx react-native android` now it says the command is unrecognized. Any idea? Thanks for replying too.

**Comment by bockc** [comment] 2019-07-24 12:19
You don't need to use any other command, run the usual `react-native run-android/ios` and it should work fine. `npx react-native run-android/ios` never worked for me.
If I correctly understood what jetifier does, it simply replaces the symbols of android.support.v4 by the AndroidX ones.

In my `package.json` I simply have `"postinstall": "npx jetify"`. Even after cleaning everything, simply running `npm i` then `react-native run-android/ios` works fine for me.

**Comment by Luckygirlllll** [comment] 2019-07-24 12:23
@bockc  I have this error in ExpoKit project,  can I use jetify in ExpoKit?

**Comment by bockc** [comment] 2019-07-26 08:34
@Luckygirlllll we don't use Expo, I don't know

**Comment by vinceyuan** [comment] 2019-07-31 00:38
I had the same errors when I compiled code in Android Studio

> @react-native-community/geolocation/android/src/main/java/com/reactnativecommunity/geolocation/GeolocationModule.java:21: error: package android.support.v4.content does not exist
> import android.support.v4.content.ContextCompat;
> ^

But after I compiled with command line `react-native run-android`, it disappeared. I saw the script used jetifier

> info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 899 file(s) to forward-jetify. Using 12 workers...

**Comment by Luckygirlllll** [comment] 2019-07-31 06:30
Just use jetify

**Comment by shushanth** [comment] 2019-08-01 09:15
Was having the same problem with RN 59+, 

npm install jetifier
npx jetify

and also added  below for androidX in`gradle.properties` 
android.useAndroidX=true
android.enableJetifier=true

**Comment by michael-harley** [comment] 2019-08-01 16:11
> Was having the same problem with RN 59+,
> 
> **npm install jetifier npx jetify**
> 
> and also make sure to add below for androidX in`gradle.properties`
> 
> **android.useAndroidX=true android.enableJetifier=true**

This is working like magic! Thanks!

**Comment by matt-oakes** [comment] 2019-08-02 01:04
Unfortunately, it's not magic. It's just part of the AndroidX migration process. You can read more about it here:

https://developer.android.com/jetpack/androidx/migrate

If you are using Jetifier, then you need to migrate to AndroidX using that guide. It's also part of the React Native 0.60 upgrade process 👍

**Comment by michael-harley** [comment] 2019-08-02 02:21
Yeah, it's just that I have tried lots of solution out there for hours, and this one is really the one that I needed.

And I have never use Android Studio, so I still don't quite get the java module used in Android. 😥

I'm one of those React developer, trying out React Native. 😁

**Comment by koudai908** [comment] 2019-08-08 09:49
just change "import android.support.v4.content.ContextCompat;" to "import androidx.core.content.ContextCompat;"
Then build in android studio.
it works.

**Comment by bobber205** [comment] 2019-09-23 22:09
Anyone else seen this when USING useAndroidX and enableJetifier set to true?

**Comment by shivaping** [comment] 2019-10-03 15:09
Still it doesnt work

**Comment by mbrucher** [comment] 2019-11-04 19:26
Quite annoying to see this closed when the problem is on the module code side :(

**Comment by 18bhavna** [comment] 2019-11-28 11:03
I am using patches as well. But running patches as well as the postinstall script seems to break the library.

**Comment by iamfindingway** [comment] 2020-06-15 06:35
I use the 'npm install jetifier npx jetify'，and add  'android.useAndroidX=true
android.enableJetifier=true' in ingradle.properties，but it do not work .Node stays in 'loading dependency graph, done' and do not proceed.What's the reason for this?@bockc

**Comment by kukuandroid** [comment] 2020-08-10 23:39
@koudai908 hi, how do you build it with android studio ? thanks

**Comment by edwinhdz307** [comment] 2020-09-02 19:54
> @msqar If I remember correctly you need to jetify your project to fully support AndroidX. Try `npm i -D jetifier ; npx jetify`. If you correctly configured your android project to use AndroidX, this should fix the last issues. Let me know if this worked.

Works for me! Thanks

**Comment by Alijadardan** [comment] 2021-01-27 14:17
> @msqar If I remember correctly you need to jetify your project to fully support AndroidX. Try `npm i -D jetifier ; npx jetify`. If you correctly configured your android project to use AndroidX, this should fix the last issues. Let me know if this worked.

You are a hero, work like a charm thank you very much!

**Comment by tgreco** [comment] 2021-03-26 17:13
> Was having the same problem with RN 59+,
> 
> **npm install jetifier npx jetify**
> 
> and also make sure to add below for androidX in`gradle.properties`
> 
> **android.useAndroidX=true android.enableJetifier=true**

Are you adding this to your gradle.properties for the project or to the node_module?

**Comment by hugoh59** [comment] 2021-06-24 07:54
Tried everything, still not working.

**Comment by SamrawitMM** [comment] 2022-01-03 11:56
Replacing the import import android.support.v4.content.ContextCompat; with import androidx.core.content.ContextCompat;  fixes the error.
